// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tgshonwmthturuxeceqr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRnc2hvbndtdGh0dXJ1eGVjZXFyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcwMDczNDAsImV4cCI6MjA3MjU4MzM0MH0.qJjMcYCkOKQsW2qmN1ptHSD1erQE16l5LHV0Wq4FW4A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});